testset:
	python3 dataprep.py --data ../data/test_identity.csv \
../data/test_transaction.csv --match TransactionID -w -o ../data


trainset:
	python3 dataprep.py --data ../data/train_identity.csv \
../data/train_transaction.csv --match TransactionID -w -o ../data
