testset:
	python3 dataprep.py --data ../data/test_transaction.csv \
	../data/test_identity.csv --match TransactionID -w -o ../data


trainset:
	python3 dataprep.py --data ../data/train_transaction.csv \
	../data/train_identity.csv --match TransactionID -w -o ../data
